services:
  - type: web
    name: airtable-form-builder-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: AIRTABLE_CLIENT_ID
        sync: false
      - key: AIRTABLE_CLIENT_SECRET
        sync: false
      - key: AIRTABLE_REDIRECT_URI
        value: http://localhost:5000/auth/callback
      - key: SESSION_SECRET
        sync: false
